Repository apple/swift-metrics, pull requests merged in 2025-03, with the labels that each got.

#162 Rename nightly_6_1 params to nightly_next
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#163 Only apply standard swift settings on valid targets
  Package.swift
Labels: semver/none

#140 Add `Timer.measure` methods
  Sources/Metrics/Metrics.swift
  Tests/MetricsTests/MetricsTests.swift
Labels: 🆕 semver/minor

#168 Fix 5.10 compile on Ubuntu 24.04
  Sources/Metrics/Metrics.swift
Labels: 🔨 semver/patch

#169 Enable macOS CI on merge to main and daily timer
  .github/workflows/main.yml
Labels: semver/none
